# Generated by Django 4.1.3 on 2025-09-23 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_language_languagelevel_level_delete_user_and_more'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_started', models.BooleanField(default=False)),
                ('language_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.languagelevel', verbose_name='language level')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.scenario', verbose_name='scenario')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.theme', verbose_name='theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['id'],
            },
        ),
    ]
