# Generated by Django 4.1.3 on 2024-10-03 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('conversations', '0001_initial'),
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='language_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.languagelevel', verbose_name='language level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.scenario', verbose_name='scenario'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.theme', verbose_name='theme'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
