# Generated by Django 4.1.3 on 2025-10-13 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='language_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.languagelevel', verbose_name='language level'),
        ),
        migrations.AddField(
            model_name='chat',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.scenario', verbose_name='scenario'),
        ),
        migrations.AddField(
            model_name='chat',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.theme', verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
