# Generated by Django 4.1.3 on 2024-10-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_chat_is_started_chat_language_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_started',
        ),
        migrations.AddField(
            model_name='chat',
            name='introduction',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
