# Generated by Django 4.1.3 on 2025-10-13 19:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='titles')),
            ],
            options={
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='titles')),
                ('teacher_role', models.CharField(max_length=255, verbose_name='teacher_roles')),
                ('student_role', models.CharField(max_length=255, verbose_name='student_roles')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.theme', verbose_name='themes')),
            ],
            options={
                'verbose_name_plural': 'Scenarios',
            },
        ),
    ]
