# Generated by Django 4.1.3 on 2025-10-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_languagelevel_speechpractices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVocabularyWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('learning_status', models.CharField(choices=[('not_learned', 'Not Learned'), ('in_progress', 'In Progress'), ('learned', 'Learned')], default='not_learned', max_length=20, verbose_name='learning_status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'User vocabulary words',
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('word', models.CharField(max_length=255)),
                ('german_translation', models.CharField(max_length=255)),
                ('czech_translation', models.CharField(max_length=255)),
                ('creator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.level', verbose_name='levels')),
                ('theme', models.ManyToManyField(blank=True, to='conversations.theme', verbose_name='themes')),
            ],
            options={
                'verbose_name_plural': 'Vocabulary words',
            },
        ),
        migrations.CreateModel(
            name='VocabularyPractice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users')),
                ('words', models.ManyToManyField(to='vocabulary.vocabularyword', verbose_name='vocabulary_words')),
            ],
            options={
                'verbose_name_plural': 'Vocabulary practices',
            },
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.language', verbose_name='languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
                ('vocabulary_words', models.ManyToManyField(to='vocabulary.uservocabularyword', verbose_name='vocabulary_words')),
            ],
            options={
                'verbose_name_plural': 'Vocabulary lists',
            },
        ),
        migrations.AddField(
            model_name='uservocabularyword',
            name='vocabulary_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularyword', verbose_name='vocabulary_word'),
        ),
        migrations.AlterUniqueTogether(
            name='uservocabularyword',
            unique_together={('user', 'vocabulary_word')},
        ),
    ]
