# Generated by Django 4.1.3 on 2025-11-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_uservocabularyword_learning_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularylist',
            name='vocabulary_words',
        ),
        migrations.AddField(
            model_name='uservocabularyword',
            name='is_selected_for_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocabularylist',
            name='user_vocabulary_words',
            field=models.ManyToManyField(to='vocabulary.uservocabularyword', verbose_name='user_vocabulary_words'),
        ),
    ]
