# Generated by Django 4.1.3 on 2025-11-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_remove_vocabularylist_vocabulary_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularylist',
            name='user_vocabulary_words',
        ),
        migrations.AddField(
            model_name='vocabularylist',
            name='user_vocabulary_word',
            field=models.ManyToManyField(blank=True, null=True, to='vocabulary.uservocabularyword', verbose_name='user_vocabulary_words'),
        ),
        migrations.AlterField(
            model_name='vocabularypractice',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, to='vocabulary.vocabularyword', verbose_name='vocabulary_words'),
        ),
    ]
