# Generated by Django 4.1.3 on 2025-11-16 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0004_remove_vocabularylist_user_vocabulary_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularypractice',
            name='words',
        ),
        migrations.AddField(
            model_name='vocabularypractice',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabularypractice',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='vocabularypractice',
            name='time_length',
            field=models.IntegerField(default=0, verbose_name='time_length'),
        ),
        migrations.AddField(
            model_name='vocabularypractice',
            name='user_vocabulary_words',
            field=models.ManyToManyField(blank=True, null=True, to='vocabulary.uservocabularyword', verbose_name='user_vocabulary_words'),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='user_vocabulary_word',
            field=models.ManyToManyField(blank=True, to='vocabulary.uservocabularyword', verbose_name='user_vocabulary_words'),
        ),
        migrations.RemoveField(
            model_name='vocabularypractice',
            name='user',
        ),
        migrations.AddField(
            model_name='vocabularypractice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
