# Generated by Django 4.1.3 on 2025-10-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagelevel',
            name='speechPractices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='totalStudyTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='vocabularyPractices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='vocabularyWords',
            field=models.IntegerField(default=0),
        ),
    ]
