# Generated by Django 4.1.3 on 2025-09-23 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.language', verbose_name='language')),
            ],
            options={
                'verbose_name_plural': 'Language levels',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ABC_value', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.level', verbose_name='level'),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
